#!/bin/bash
# =============================================================================
# Spawn Machine — Agent Factory CLI
#
# Spawn, configure, register, and manage AI agent desktop instances.
#
# Usage:
#   spawn-machine.sh <command> [agent-name] [options]
#
# Commands:
#   init <name>       Create incubator directory + agent spec template
#   configure <name>  Generate env vars from agent spec
#   register <name>   Register agent in Guacamole Full
#   validate <name>   Run health checks on a deployed agent
#   status [name]     Show status of one or all agents
#   list              List all agents in the incubator
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="${WORKSPACE:-/home/developer/.openclaw/workspace}"
INCUBATOR_DIR="${WORKSPACE}/platform/incubator"
REGISTRY_FILE="${INCUBATOR_DIR}/registry.yaml"

# Load configs
GUACAMOLE_CREDS="${HOME}/.config/guacamole/config"
COOLIFY_CREDS="${HOME}/.config/coolify/config"

# =============================================================================
# Helpers
# =============================================================================
log() { echo "[spawn-machine] $*"; }
err() { echo "[spawn-machine] ERROR: $*" >&2; }

load_guacamole_creds() {
    if [ ! -f "${GUACAMOLE_CREDS}" ]; then
        err "Guacamole credentials not found at ${GUACAMOLE_CREDS}"
        err "Create with: GUACAMOLE_URL, GUACAMOLE_USER, GUACAMOLE_PASS"
        return 1
    fi
    source "${GUACAMOLE_CREDS}"
}

guacamole_token() {
    local token
    token=$(curl -s -X POST "${GUACAMOLE_URL}/api/tokens" \
        -d "username=${GUACAMOLE_USER}&password=${GUACAMOLE_PASS}" | jq -r '.authToken')
    if [ -z "${token}" ] || [ "${token}" = "null" ]; then
        err "Failed to get Guacamole auth token"
        return 1
    fi
    echo "${token}"
}

require_agent_name() {
    if [ -z "${1:-}" ]; then
        err "Agent name required. Usage: spawn-machine.sh $COMMAND <agent-name>"
        exit 1
    fi
}

# =============================================================================
# Commands
# =============================================================================

cmd_init() {
    local name="$1"
    local agent_dir="${INCUBATOR_DIR}/${name}"

    if [ -d "${agent_dir}" ]; then
        err "Agent '${name}' already exists at ${agent_dir}"
        exit 1
    fi

    log "Initializing agent '${name}'..."
    mkdir -p "${agent_dir}"

    # Create agent spec from template
    cat > "${agent_dir}/agent-spec.md" << SPEC
---
created: $(date -Iseconds)
status: INITIALIZED
agentName: ${name}
stepsCompleted: ['init']
---

# Agent Spec: ${name}

## Identity
- **Name:** ${name}
- **Purpose:** (to be defined)
- **Operator:** (to be defined)
- **Timezone:** CET
- **Specialties:** (to be defined)
- **Vibe:** (to be defined)

## Boundaries
(to be defined)

## Services
(use 'spawn-machine.sh configure ${name}' after filling in the spec)

## Environment
(generated by configure command)
SPEC

    log "Created ${agent_dir}/agent-spec.md"
    log "Next: Edit the agent spec, then run 'spawn-machine.sh configure ${name}'"
}

cmd_configure() {
    local name="$1"
    local agent_dir="${INCUBATOR_DIR}/${name}"
    local spec="${agent_dir}/agent-spec.md"

    if [ ! -f "${spec}" ]; then
        err "Agent spec not found: ${spec}"
        err "Run 'spawn-machine.sh init ${name}' first"
        exit 1
    fi

    log "Generating env vars for '${name}'..."

    cat > "${agent_dir}/env-vars.md" << ENV
# ${name} — Coolify Environment Variables

Generated: $(date -Iseconds)

## Coolify App Settings
- **Repo:** machine-machine/m2-desktop
- **Branch:** guacamole
- **Docker Compose Location:** /docker-compose.agent.yml
- **Consistent Container Name:** ${name}-desktop

## Environment Variables

| Variable | Value |
|----------|-------|
| AGENT_NAME | ${name} |
| AGENT_CONFIG_GENERATE | true |
| CLAWDBOT_HOME | /clawdbot_home |
| M2_VARIANT | guacamole |
| WORKSPACE | /home/developer/.openclaw/workspace |
| ANTHROPIC_API_KEY | (set in Coolify) |
| VNC_PASSWORD | $(openssl rand -base64 24 | tr -d '/+=') |
| AGENT_OPENCLAW_REPO | https://github.com/machine-machine/openclaw.git |
| AGENT_OPENCLAW_BRANCH | m2-custom |
| AGENT_BOOTSTRAP_REPO_URL | https://raw.githubusercontent.com/machine-machine/m2-desktop/guacamole/incubator/${name} |
| QDRANT_URL | http://memory-qdrant:6333 |
| EMBEDDINGS_URL | http://memory-embeddings:8000 |
| AGENT_ID | ${name} |
| COLLECTION_NAME | agent_memory |
| AGENT_STT_BASE_URL | http://speaches-l0w808o4k80k0gogg88s80cc:8000/v1 |
| AGENT_STT_MODEL | whisper-1 |
| AGENT_SKILLS | xfce-desktop,m2-memory |
| AGENT_BROWSER_ENABLED | true |
| AGENT_CPUS | 8 |
| AGENT_MEMORY | 8g |
| SHM_SIZE | 1gb |

## Guacamole Registration

| Setting | Value |
|---------|-------|
| Connection Name | ${name^} Desktop |
| Protocol | VNC |
| Hostname | ${name}-desktop |
| Port | 5900 |
| Password | (from VNC_PASSWORD above) |
ENV

    log "Generated ${agent_dir}/env-vars.md"
    log "Review the env vars, then set them in Coolify and deploy."
}

cmd_register() {
    local name="$1"
    local agent_dir="${INCUBATOR_DIR}/${name}"

    load_guacamole_creds || exit 1

    # Try to read VNC password from env-vars.md
    local vnc_pass=""
    if [ -f "${agent_dir}/env-vars.md" ]; then
        vnc_pass=$(grep "VNC_PASSWORD" "${agent_dir}/env-vars.md" | grep -oP '\| \K[^|]+$' | xargs || true)
    fi
    if [ -z "${vnc_pass}" ] || [ "${vnc_pass}" = "(set in Coolify)" ]; then
        read -rp "VNC password for ${name}-desktop: " vnc_pass
    fi

    log "Getting Guacamole auth token..."
    local token
    token=$(guacamole_token) || exit 1

    log "Creating VNC connection for '${name}'..."
    local response
    response=$(curl -s -X POST "${GUACAMOLE_URL}/api/session/data/mysql/connections?token=${token}" \
        -H "Content-Type: application/json" \
        -d "{
            \"name\": \"${name^} Desktop\",
            \"protocol\": \"vnc\",
            \"parentIdentifier\": \"ROOT\",
            \"parameters\": {
                \"hostname\": \"${name}-desktop\",
                \"port\": \"5900\",
                \"password\": \"${vnc_pass}\",
                \"color-depth\": \"32\",
                \"width\": \"1920\",
                \"height\": \"1080\",
                \"dpi\": \"96\"
            },
            \"attributes\": {}
        }")

    local conn_id
    conn_id=$(echo "${response}" | jq -r '.identifier // empty')

    if [ -n "${conn_id}" ]; then
        log "Registered! Connection ID: ${conn_id}"
        log "Access: ${GUACAMOLE_URL} → ${name^} Desktop"
    else
        err "Registration failed. Response: ${response}"
        exit 1
    fi
}

cmd_validate() {
    local name="$1"
    local container="${name}-desktop"
    local pass=0
    local fail=0
    local skip=0

    log "Validating agent '${name}'..."
    echo ""

    # Network reachability
    printf "  %-40s" "DNS resolution (${container})..."
    if ping -c 1 -W 2 "${container}" &>/dev/null; then
        echo "PASS"
        ((pass++))
    else
        echo "FAIL"
        ((fail++))
    fi

    printf "  %-40s" "VNC port (5900)..."
    if nc -z -w 2 "${container}" 5900 &>/dev/null; then
        echo "PASS"
        ((pass++))
    else
        echo "FAIL"
        ((fail++))
    fi

    printf "  %-40s" "guacd port (4822)..."
    if nc -z -w 2 "${container}" 4822 &>/dev/null; then
        echo "PASS"
        ((pass++))
    else
        echo "FAIL"
        ((fail++))
    fi

    # Memory system
    printf "  %-40s" "Qdrant reachable..."
    if curl -s -o /dev/null -w '%{http_code}' http://memory-qdrant:6333/collections | grep -q "200"; then
        echo "PASS"
        ((pass++))
    else
        echo "FAIL"
        ((fail++))
    fi

    printf "  %-40s" "Embeddings reachable..."
    if curl -s -o /dev/null -w '%{http_code}' http://memory-embeddings:8000/health 2>/dev/null | grep -q "200"; then
        echo "PASS"
        ((pass++))
    else
        echo "SKIP (may not have /health)"
        ((skip++))
    fi

    echo ""
    echo "  Results: ${pass} passed, ${fail} failed, ${skip} skipped"

    if [ "${fail}" -eq 0 ]; then
        log "Validation PASSED"
    else
        log "Validation FAILED (${fail} issues)"
        exit 1
    fi
}

cmd_status() {
    local name="${1:-}"

    if [ -n "${name}" ]; then
        local container="${name}-desktop"
        printf "  %-15s" "${name}"

        if ping -c 1 -W 1 "${container}" &>/dev/null; then
            if nc -z -w 1 "${container}" 4822 &>/dev/null; then
                echo "OPERATIONAL  ${container}"
            else
                echo "UNHEALTHY    ${container}  (guacd not responding)"
            fi
        else
            echo "UNREACHABLE  ${container}"
        fi
    else
        log "Agent Status:"
        echo ""
        for dir in "${INCUBATOR_DIR}"/*/; do
            [ -d "${dir}" ] || continue
            local agent_name
            agent_name=$(basename "${dir}")
            # Skip non-agent dirs
            [ "${agent_name}" = "spawn-machine" ] && continue
            cmd_status "${agent_name}" 2>/dev/null || true
        done
    fi
}

cmd_list() {
    log "Agents in incubator:"
    echo ""
    for dir in "${INCUBATOR_DIR}"/*/; do
        [ -d "${dir}" ] || continue
        local agent_name
        agent_name=$(basename "${dir}")
        [ "${agent_name}" = "spawn-machine" ] && continue

        local status="unknown"
        if [ -f "${dir}/agent-spec.md" ]; then
            status=$(grep "^status:" "${dir}/agent-spec.md" | head -1 | sed 's/status: *//' || echo "unknown")
        fi
        printf "  %-15s %s\n" "${agent_name}" "${status}"
    done
}

# =============================================================================
# Main
# =============================================================================
COMMAND="${1:-help}"
shift || true

case "${COMMAND}" in
    init)
        require_agent_name "${1:-}"
        cmd_init "$1"
        ;;
    configure)
        require_agent_name "${1:-}"
        cmd_configure "$1"
        ;;
    register)
        require_agent_name "${1:-}"
        cmd_register "$1"
        ;;
    validate)
        require_agent_name "${1:-}"
        cmd_validate "$1"
        ;;
    status)
        cmd_status "${1:-}"
        ;;
    list)
        cmd_list
        ;;
    help|--help|-h)
        echo "Spawn Machine — Agent Factory CLI"
        echo ""
        echo "Usage: spawn-machine.sh <command> [agent-name]"
        echo ""
        echo "Commands:"
        echo "  init <name>       Create incubator directory + agent spec"
        echo "  configure <name>  Generate env vars from agent spec"
        echo "  register <name>   Register agent in Guacamole"
        echo "  validate <name>   Run health checks on deployed agent"
        echo "  status [name]     Show status of one or all agents"
        echo "  list              List all agents in incubator"
        ;;
    *)
        err "Unknown command: ${COMMAND}"
        err "Run 'spawn-machine.sh help' for usage"
        exit 1
        ;;
esac
